### ISSUE TITLE
Monero GUI wallet Linux only app-image??

### ISSUE THREAD

**Issue by ITnotsavvy01** [deverickapollo/umbrel-monero#139]
Hi there,

Can I ask a question about the Linux Monero GUI wallet?

Recently I switched to a Linux computer and have a Monero GUI wallet now. The only issue is that it is a app image download, and not from the Linux 'app-store', so no automatic updates. In the Linux app-store there was only the complete Monero download including the blockchain. 

Is there a secure Monero GUI wallet download available which is a flat-pack or something??

If not, how should I deal with any necessary updates?

Thx in advance for your help?

**Comment by Ace19745** [comment]
A complaint has be lodged and ticket has been created for you (Ticket number #Mw62892)
Visit the official website to initiate a chat with the support team via [Monero wallet Live chat](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generate for you to properly update your version

**Comment by deverickapollo** [comment]
Please refer to the monero-project github for the latest image releases.  You can find all images [here](https://github.com/monero-project/monero-gui?tab=readme-ov-file#installing-the-monero-gui-from-a-package). The flatpack version is listed and redirects to [flathub](https://flathub.org/apps/org.getmonero.Monero). I'll close this issue for now.
