### ISSUE TITLE
App wont install on x86 Umbrel

### ISSUE THREAD

**Issue by examare** [deverickapollo/umbrel-monero#75]
App install, 2 attempts have failed on Debian x86 Umbrell, this system is already ready running an x86 monerod service (could is this be an issue ?)

**Comment by deverickapollo** [comment]
It could be failing to bind to the default ports.  Are you using ports 18081 and 18082? 

Running the install from CLI will give you some more information on the failure.  You can do this by running `sudo ./scripts/app meganero-monero` from the umbrel directory then check running processes with `sudo docker ps`.  You can also follow the logs for any container via `docker logs --follow container-name`. 

I'd recommend stopping the existing monerod instance, installing the app, stopping the app via cli - `sudo ./scripts/app stop meganero-monero` then replacing the lmdb files in`umbrel/app-data/meganero-monero/data/monero` with your copy.  After that, you can start the app again from CLI - `sudo ./scripts/app start meganero-monero`

**Comment by examare** [comment]
Got it installed, I killed existing monerod, but the gui install seemed stuck so I ran `sudo ./scripts/app install meganero-monero` via cli and that did the trick!
