### ISSUE TITLE
Unable to allow incoming connections

### ISSUE THREAD

**Issue by MerQel** [deverickapollo/umbrel-monero#84]
First off, thanks for creating this app!

I have an issue where I'm unable to allow incoming connections.

My node is fully synced
Advanced Settings -> Enable Incoming connections -> Save and restart monero node
Red bar appears - 'Something went wrong while attempting to change the configuration of Monero Node. '

The issue persists after rebooting

**Comment by deverickapollo** [comment]
Thanks for submitting. I'm working on a couple bug fixes and this one should be resolved on the next release.  I'll reach out when that's ready. Thanks for reporting!

**Comment by deverickapollo** [comment]
This issue should be resolved in our latest release. Please update the app and retest to confirm the fix. 

If the issue continues, you will need to restore the configuration to its default settings. You can do this from the UI - Advanced settings page or directly on the node via ssh. The path to the monero config file is `$HOME/umbrel/app-data/meganero-monero/data/monero`. 

Tip: View logs for monerod by running `sudo docker logs --follow meganero-monero_server_1` while logged into the remote node.

**Comment by deverickapollo** [comment]
This issue should be resolved in our latest release. Please update the app and retest to confirm the fix.

If the issue continues, you will need to restore the configuration to its default settings. You can do this from the UI - Advanced settings page or directly on the node via ssh. The path to the monero config file is $HOME/umbrel/app-data/meganero-monero/data/monero.

Tip: View logs for monerod by running sudo docker logs --follow meganero-monero_server_1 while logged into the remote node.
