### ISSUE TITLE
Monero Node stuck starting

### ISSUE THREAD

**Issue by glgamsh** [deverickapollo/umbrel-monero#85]

**Comment by deverickapollo** [comment]
Hi - can you provide steps so I can replicate this issue?  Thanks!

**Comment by glgamsh** [comment]
due to a faulty cable, the umbrel os server crashed numerous times and to reset it the only way was to unplug the cable and reconnect it. one day the problem arose.

**Comment by deverickapollo** [comment]
Hey @glgamsh - Can you log into the machine via ssh and capture a log of monerod? You can see the logs for monerod by running `sudo docker logs --follow  meganero-monero_monerod_1`

You may have a corrupt chain.  If so, we can update you to the latest release and attempt a database salvage.

**Comment by deverickapollo** [comment]
Please reopen if you need more assistance. Closing as complete
